/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGarfica;

import agendaPrincipal.Agenda;

import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author rosane
 */
public class JFrameInterface extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInterface
     */
    public JFrameInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton1)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInterface().setVisible(true);
            }
        });
        
        String continuar="s",listarContatos;
        int opcao;
        
        Contato contatoAux;
        
        Arquivo agendaPessoal = new Arquivo();
        
        Scanner scanner = new Scanner(System.in);
       
        ArrayList<Contato> contatos = new ArrayList<>();

        
        while(continuar.equals("s")){
            
            System.out.println("O que deseja fazer?");
            System.out.println("Digite 1 para adicionar contato.\n"
                + "Digite 2 para alterar algum contato.\n"
                + "Digite 3 para pesquisar um contato.");
            opcao = scanner.nextInt();
            scanner.nextLine();
            
            switch (opcao){
                case 1:
                    contatoAux=new Contato();
                    contatoAux.AdicionaContato();
                    contatos.add(contatoAux);
                    
                    
                break;
                
                case 2:
                    
                    System.out.println("Qual o nome do contato a ser alterado?");
                    String nomeAux ;
                    nomeAux = scanner.nextLine();
                    
                    boolean contatoLocalizado=false;
                    //System.out.println(contatos.size());
                    for (int i = 0; i < contatos.size(); i++) {
                        System.out.println(contatos.size());
                        if(contatos.get(i).getNome().equals(nomeAux)){
                            contatoAux = new Contato();
                            contatoAux.AdicionaContato();
                            contatos.remove(i);
                            contatos.add(contatoAux);
                            contatoLocalizado=true;
                        }
                    }
                    if (!contatoLocalizado){
                        System.out.println("Contato Inexistente.");
                    }    
                    
                break;
                
                case 3:
                    
                    System.out.println("Digite 1 para pesquisar por nome e 2 para pesquisar"
                            + "por número.");
                    int pesquisa = scanner.nextInt();
                    scanner.nextLine();
                    
                    if (pesquisa==1){
                        System.out.println("Digite o nome da pessoa:");
                        nomeAux = scanner.nextLine();
                        for (int i = 0; i < contatos.size(); i++) {
                            if(nomeAux.equals(contatos.get(i).getNome())){
                                System.out.println("Nome: " + contatos.get(i).getNome());
                                System.out.println("Numero: " + contatos.get(i).getNumero());
                                System.out.println("Endereço: " + contatos.get(i).getEndereco());
                                System.out.println("E-mail: " + contatos.get(i).getEmail());
                            }
                        }
                    }
                    if (pesquisa==2){
                        System.out.println("Digite o numero da pessoa:");
                        int numero = scanner.nextInt();
                        for (int i = 0; i < contatos.size(); i++) {
                            if(numero == contatos.get(i).getNumero()){
                                System.out.println("Nome: " + contatos.get(i).getNome());
                                System.out.println("Numero: " + contatos.get(i).getNumero());
                                System.out.println("Endereço: " + contatos.get(i).getEndereco());
                                System.out.println("E-mail: " + contatos.get(i).getEmail());
                            }
                        }
                    }
                    
                break;
               
            }
            System.out.println("Deseja continuar utilizando a agenda? (s/n)");
            continuar = scanner.nextLine();    
            
        }
        for (int i = 0; i < contatos.size(); i++) {
            agendaPessoal.EscreverArquivo(contatos.get(i));
        }
        agendaPessoal.encerrarEscrita();
        
        System.out.println("Deseja Listar contatos?(s/n)");
        listarContatos = scanner.nextLine();
        if(listarContatos.equals("s")){
            agendaPessoal.LerArquivo();
        }
        agendaPessoal.encerrarLeitura();
       
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
